### ISSUE TITLE
Add ability to save visualization data and connect to existing database.

### ISSUE THREAD

**Issue by dsmueller3760** [gabrielchua/RAGxplorer#31]
**Is your feature request related to a problem? Please describe.**
Having to load a PDF every time you use the tool can take a long time. It is also useful to look at multiple PDFs. Furthermore, since UMAP is stochastic, having the ability to reproduce results would be helpful for those performing studies.

**Describe the solution you'd like**
Add functionality to connect to existing chromadb's.
Add export functionality for the UMAP function and projections, which can be re-read in.

**Describe alternatives you've considered**
I have created a forked version of this repository which performs these tasks: https://github.com/dsmueller3760/RAGxplorer/tree/load_db (under load_db branch).

**Additional context**
N/A

**Comment by gabrielchua** [comment]
These are great suggestions! Thanks @dsmueller3760 

Do you want to take it on and make a PR?

The api could be like this?

What do you think?

```python
from ragxplorer import RAGxplorer
client = RAGxplorer(embedding_model="thenlper/gte-large")
client.load_db("presentation.pdf", verbose=True)

chroma_client = client.export_client()
projector = client.export_projector()

new_client = RAGxplorer(embedding_model="thenlper/gte-large")
new_client.load_db(chroma_client)
new_client.load_projector(projector)

```

**Comment by gabrielchua** [comment]
Tried something here. @dsmueller3760 

Let me know whatcha think.

https://github.com/gabrielchua/RAGxplorer/blob/main/ragxplorer/ragxplorer.py

**Comment by dsmueller3760** [comment]
You beat me to the punch :). I'll test this out this weekend.

I can create a new issue (lmk), but also found that along the way to using this functionality, it's useful to be able to pass along the UMAP parameters when initializing the UMAP. E.g. setting the random seed ensures reproducable results every time you run the function. Passing a dict wiht the paramers would suffice.
