### ISSUE TITLE
Sweep: RAGxplorer Demo link in README not working

### ISSUE THREAD

**Issue by deveshXm** [gabrielchua/RAGxplorer#41]
### Details
README.txt : Demo url link is not working. replace it with working url.

<details open>
<summary>Checklist</summary>

- [X] Modify `README.md` ✓ https://github.com/gabrielchua/RAGxplorer/commit/79dd9e0da484da3e3d2788cb31eccdd99c4bb2ee [Edit](https://github.com/gabrielchua/RAGxplorer/edit/sweep/ragxplorer_demo_link_in_readme_not_worki/README.md#L37-L37)
- [X] Running GitHub Actions for `README.md` ✓  [Edit](https://github.com/gabrielchua/RAGxplorer/edit/sweep/ragxplorer_demo_link_in_readme_not_worki/README.md#L37-L37)
</details>

**Comment by gabrielchua** [comment]
Hi, the demo is available at https://ragxplorer.streamlit.app/. Thanks!
