### ISSUE TITLE
Add a link or button to reset the form so you can upload a new document after analyzing an initial document

### ISSUE THREAD

**Issue by tedsecretsource** [gabrielchua/RAGxplorer#8]
**Is your feature request related to a problem? Please describe.**
Currently, once you upload and analyze a document, you have to refresh the application to analyze a new document. This is a request to add a button or link to the form so you can more easily analyze a new document.

**Describe the solution you'd like**
Add a link to the upper left-hand corner (in the header) to go back to the main form.

**Describe alternatives you've considered**
display the whole form below the graph

**Comment by gabrielchua** [comment]
This can be done pretty fast! Will work on it ~

thanks

**Comment by gabrielchua** [comment]
Added via #11 - thanks!

reset button is next to `search`

<img width="1355" alt="Screenshot 2024-01-25 at 12 50 57 AM" src="https://github.com/gabrielchua/RAGxplorer/assets/34762009/b4069191-e67c-41ec-bd49-8ab98c0bcea4">
